title: Digital Literacty for the Performing Arts
email: laurent.pugin@wbkolleg.unibe.ch
description: "DLPA 2020"
repository: DHBern/DLPA2020
github: [metadata]

# Build settings
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

logo: "/images/logo.png"

footer:
  links:
    - label: "Web"
      icon: "fa fa-fw fa-home"
      url: "https://dh.unibe.ch"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dhbern/dlpa2020"


defaults:
  -
    scope:
      path: ""
    values:
      header:
        overlay_image: /images/header.png
        overlay_filter: 0.5 # same as adding an opacity of 0.5 to a black background
  -
    scope:
      path: "day1"
    values:
      sidebar:
        nav: "day1"
  -
    scope:
      path: "day2"
    values:
      sidebar:
        nav: "day2"